REST API Basics
DmitryAkulich33/mjc_module_02_task_01 pull request #1
Opened 2020-10-21 19:22 UTC by DmitryAkulich33

added: dao (not all), domain , mapper, sql scripts

2020-10-26 18:06 UTC, sznv requested changes

2020-10-26 18:53 UTC, DmitryAkulich33 commented on rest/build/resources/main/sql/3_create_tables.sql
> +    id_tag INTEGER NOT NULL AUTO_INCREMENT,
Done!

2020-10-26 18:54 UTC, DmitryAkulich33 commented on rest/src/main/java/com/epam/esm/Application.java
> +public class Application {
Done!

2020-10-26 18:56 UTC, DmitryAkulich33 commented on rest/src/main/java/com/epam/esm/controller/CertificateController.java
> +    public List<Certificate> deleteById (@PathVariable int id){
Done!

2020-10-26 19:20 UTC, DmitryAkulich33 commented on rest/src/main/java/com/epam/esm/dao/impl/CertificateDaoImpl.java
> +    private static final String FIND_BY_ID = "SELECT * FROM certificate WHERE id_certificate=? AND lock_certificate=0";
Done!

2020-10-28 20:07 UTC, DmitryAkulich33 commented on rest/src/main/java/com/epam/esm/config/SpringConfig.java
> +public class SpringConfig implements WebMvcConfigurer {
Done

2020-10-28 20:07 UTC, DmitryAkulich33 commented on rest/src/main/java/com/epam/esm/controller/CertificateController.java
> +@RequestMapping(value = "/certificate", produces = MediaType.APPLICATION_JSON_VALUE)
Done

2020-10-28 20:07 UTC, DmitryAkulich33 commented on rest/src/main/java/com/epam/esm/controller/CertificateController.java
> +@RequestMapping(value = "/certificate", produces = MediaType.APPLICATION_JSON_VALUE)
Done

2020-10-28 20:07 UTC, DmitryAkulich33 commented on rest/src/main/java/com/epam/esm/controller/CertificateController.java
> +    public List<Certificate> deleteById (@PathVariable int id){
Done

2020-10-28 20:07 UTC, DmitryAkulich33 commented on rest/src/main/java/com/epam/esm/config/SpringConfig.java
> +    }
Done

2020-10-28 20:08 UTC, DmitryAkulich33 commented on rest/src/main/java/com/epam/esm/controller/CertificateController.java
> +public class CertificateController {
Done

2020-10-28 20:08 UTC, DmitryAkulich33 commented on rest/src/main/java/com/epam/esm/controller/CertificateController.java
> +public class CertificateController {
Done

2020-10-28 20:08 UTC, DmitryAkulich33 commented on rest/src/main/java/com/epam/esm/controller/CertificateController.java
> +    public List<Certificate> add (@RequestBody Certificate certificate){
Done

2020-10-28 20:08 UTC, DmitryAkulich33 commented on rest/src/main/java/com/epam/esm/controller/CertificateController.java
> +public class CertificateController {
Done

2020-10-28 20:08 UTC, DmitryAkulich33 commented on rest/src/main/java/com/epam/esm/controller/CertificateController.java
> +    @GetMapping(path = "/certificates")
Done

2020-10-28 20:08 UTC, DmitryAkulich33 commented on rest/src/main/java/com/epam/esm/controller/TagController.java
> +import com.epam.esm.domain.Certificate;
Done

2020-11-04 13:15 UTC, sznv approved these changes

2020-11-04 13:15 UTC, merged